services:
  db:
    image: postgres:15-alpine
    container_name: tutoria_db_final
    restart: always
    environment:
      POSTGRES_DB: tutoria_db
      POSTGRES_USER: admin_tutoria
      POSTGRES_PASSWORD: PasswordSeguro123
    ports:
      - "5434:5432"
    volumes:
      # Se cambia el volumen nombrado 'pgdata_final' por la carpeta local 'tutores_data'
      - ./tutores_data:/var/lib/postgresql/data